name: Build And Release

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  release:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - uses: pnpm/action-setup@v2.0.1
        with:
          version: latest
          run_install: true

      - run: pnpm run build

      - uses: zkqiang/tencent-cos-action@v0.1.0
        with:
          args: upload -r ./dist/ /
          secret_id: ${{ secrets.SECRET_ID }}
          secret_key: ${{ secrets.SECRET_KEY }}
          bucket: ${{ secrets.BUCKET }}
          region: ap-shanghai
